### ISSUE TITLE
Consider fixing versions in Dockerfile

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust-test-runner#43]
Currently, the Dockerfile uses the following base images:

- rustlang/rust:nightly
- rust:latest

As seen, neither of these are pinned to a specific version. While this works, it effectively cancels any docker caching whenever those images are updated. Put differently: if only code involving the very last step of the Dockerfile was changed but the nightly release was changed (which it does, I guess, each night), this means re-building everything. This is both wasteful and very slow. Is it perhaps possible to pin these images to specific versions/commits?

**Comment by ErikSchierboom** [comment]
@ZloeSabo If you're interested, maybe you could look at this issue? It would be great if we could pin the version. That would help with reducing potential breakages and with docker layer caching.

**Comment by senekor** [comment]
We have since switched to a pinned version of Rust (6772d5168eda6ced7cf4bbf4d89251ffc18dbcb4).

One line that's still suspicious is `RUN rustup toolchain add nightly`. I think docker doesn't rerun this line on its own, right? In the [docs](https://docs.docker.com/build/cache/#how-does-the-build-cache-work), a couple paragraphs below the linked heading, there's a note which suggests `RUN` commands aren't rerun on their own. But I don't *really* understand how docker's caching works.

If I got that wrong and the nightly version should be pinned explicitly, that can be done without too much trouble.

**Comment by ErikSchierboom** [comment]
> I think docker doesn't rerun this line on its own, right? 

Correct. Do we still need the nightly version?

**Comment by senekor** [comment]
Unfortunately, yes. (https://github.com/rust-lang/rust/issues/49359)

I'm keeping an eye on `cargo-nextest` an alternative test runner. It also doesn't have json output yet, but might get it sooner. (https://github.com/nextest-rs/nextest/issues/20)

**Comment by ErikSchierboom** [comment]
Holy smokes that has been behind a flag for a long time.
