### ISSUE TITLE
allergies problem version issue (passes locally)

### ISSUE THREAD

**Issue by hotsfttac** [exercism/rust-test-runner#53]
Looks like `proc_macro2` ([link](https://docs.rs/proc-macro2/latest/proc_macro2/)) is out of date:

error: failed to select a version for the requirement `proc-macro2 = "^1.0.38"` (locked to 1.0.39)
candidate versions found which didn't match: 1.0.38
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `enum-iterator-derive v0.8.1`
    ... which satisfies dependency `enum-iterator-derive = "^0.8.1"` (locked to 0.8.1) of package `enum-iterator v0.8.1`
    ... which satisfies dependency `enum-iterator = "^0.8.1"` (locked to 0.8.1) of package `allergies v1.1.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

**Comment by ErikSchierboom** [comment]
@dhovart What would be the best way that way we force the test runner image to be rebuilt? Maybe add some version file that we can update?

**Comment by steviet91** [comment]
Hi - any updates on this one please? I have the same for both `allergies` problem and `poker`. `poker` was ok in the end as I could revert to `0.4.0` on the `int-enum` crate but `allergies` is failing as the `enum-iterator` crate available on the runner doesn't contain `Sequence` trait or the `all` function.

**Comment by ErikSchierboom** [comment]
@steviet91 We currently have an issue with the test runner's registry (in which the crates are contained) doesn't build:

https://github.com/exercism/rust-test-runner/actions/runs/3408894732

Perhaps you have an idea why?

**Comment by senekor** [comment]
I'm pretty sure the test runner has been rebuilt with more recent versions in the meantime, which should solve @steviet91's problem. Feel free to ping if you think this should stay open.

@hotsfttac's problem was most likely caused by `Cargo.lock` being submitted, which pinned the version to a higher one than the one allowed by `Cargo.toml`.

(I'm thinking about how to best update the docs, these version mismatches are a common problem and the error messages are confusing to stundents.)
