### ISSUE TITLE
Rust test runner not tracking stable?

### ISSUE THREAD

**Issue by Redundancy** [exercism/rust-test-runner#60]
Referred by: https://github.com/exercism/rust/issues/1575

TLDR: used scoped threads from 1.63 for solution, but solution is rejected as using an unstable feature.

**Comment by AdrianoII** [comment]
Apparently, we are still using 1.62 for some reason. I tried to specify the rustc version in the `Cargo.toml` and got this:

`error: package `parallel-letter-frequency v0.0.0 (/mnt/exercism-iteration)` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.62.0-nightly`

**Comment by AdrianoII** [comment]
I think that we have a dependency problem. The [last attempt](https://github.com/exercism/rust-test-runner/actions/runs/3408894732/jobs/5670008697) to push a new version failed because of a mismatch with bstr version.

**Comment by ErikSchierboom** [comment]
> I think that we have a dependency problem. The [last attempt](https://github.com/exercism/rust-test-runner/actions/runs/3408894732/jobs/5670008697) to push a new version failed because of a mismatch with bstr version

That is correct. If anyone knows a fix?

**Comment by AdrianoII** [comment]
This was fixed by #66, we can close it now.
